[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry-server"
  status = 200
