[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888

[build.environment]
  NODE_VERSION = "20"
