[build]
  # This should match your Remix output folder
  publish = "dist"
  command = "npm run build"

[dev]
  # Local dev command
  command = "npm run dev"
  port = 3000

[[redirects]]
  # SPA fallback: all routes served by index.html
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # If you have Netlify Functions (like ai-diagnose)
  directory = "netlify/functions"
